### ISSUE TITLE
Can you describe the process flow and logic a little

### ISSUE THREAD

**Issue by alanef** [SPnl/nl.sp.renewmembership#1]
Hi,

This may possible help my problem, but reading the code I can't quite work out what process flows and logic applies.  Happy to update the READ.ME for you when I understand :)

What I'm hoping is

1.  a csv of contributions  (by member) is uploaded
2. this job runs and identified the contribution (somehow?) is associated with a membership that requires renewing (now as it has expired/grace or at when it expire) and links up the contribution to the membership and renews.

How wrong am I, if I'm close happy to spend more time reading the code, just not too familiar with Civi API at the moment, having only written 1 report and one custom query

**Comment by jaapjansma** [comment]
This extension does the following:
You have a selection screen for membership type, status, end date etc.. Then all the found memberships are updated with a new end date a year later then the current end date. It will also create 4 contributions for each membership. The 4 contributions are dated on the 1st of January, 1st of April, 1st of July and 1st of October.

This extension is specific for the socialist party. 

Does this answer your question?

**Comment by alanef** [comment]
Many thanks, pretty specific, but I think there are bit I can use. thanks for publishing.

**Comment by jaapjansma** [comment]
Thanks. It is a pleasure to share
